name = "WaterLily"
uuid = "ed894a53-35f9-47f1-b17f-85db9237eebd"
authors = ["Gabriel Weymouth <drweymouth@google.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "^1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test"]
